CREATE DATABASE IF NOT EXISTS ChefMateDB
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE ChefMateDB;

CREATE TABLE IF NOT EXISTS Users (
    userId INT AUTO_INCREMENT PRIMARY KEY,
    fullName VARCHAR(100) NOT NULL,
    phone VARCHAR(15) NOT NULL UNIQUE,
    email VARCHAR(100) UNIQUE,
    passwordHash VARCHAR(255) NOT NULL,
    followCount INT DEFAULT 0,
    recipeCount INT DEFAULT 0,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Recipes (
    recipeId INT AUTO_INCREMENT PRIMARY KEY,
    recipeName VARCHAR(150) NOT NULL,
    image VARCHAR(1000) NOT NULL,
    cookingTime VARCHAR(50) NOT NULL,
    ration INT NOT NULL,
    likeQuantity INT DEFAULT 0,
    viewCount INT DEFAULT 0,
    userId INT NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES Users(userId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Tags (
    tagId INT AUTO_INCREMENT PRIMARY KEY,
    tagName VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS RecipesTags (
    rtId INT AUTO_INCREMENT PRIMARY KEY,
    recipeId INT NOT NULL,
    tagId INT NOT NULL,
    FOREIGN KEY (recipeId) REFERENCES Recipes(recipeId) ON DELETE CASCADE,
    FOREIGN KEY (tagId) REFERENCES Tags(tagId) ON DELETE CASCADE,
    UNIQUE KEY (recipeId, tagId)
);

CREATE TABLE IF NOT EXISTS Ingredients (
    ingredientId INT AUTO_INCREMENT PRIMARY KEY,
    ingredientName VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS RecipesIngredients (
    riId INT AUTO_INCREMENT PRIMARY KEY,
    recipeId INT NOT NULL,
    ingredientId INT NOT NULL,
    weight DECIMAL(10,2) DEFAULT 0,
    unit VARCHAR(20) DEFAULT '',
    FOREIGN KEY (recipeId) REFERENCES Recipes(recipeId) ON DELETE CASCADE,
    FOREIGN KEY (ingredientId) REFERENCES Ingredients(ingredientId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CookingSteps (
    csId INT AUTO_INCREMENT PRIMARY KEY,
    recipeId INT NOT NULL,
    indexStep INT NOT NULL,
    content TEXT NOT NULL,
    FOREIGN KEY (recipeId) REFERENCES Recipes(recipeId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UsersLike (
    ulId INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    recipeId INT NOT NULL,
    FOREIGN KEY (userId) REFERENCES Users(userId) ON DELETE CASCADE,
    FOREIGN KEY (recipeId) REFERENCES Recipes(recipeId) ON DELETE CASCADE,
    UNIQUE KEY (userId, recipeId)
);

CREATE TABLE IF NOT EXISTS UsersComment (
    ucId INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    recipeId INT NOT NULL,
    content TEXT NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES Users(userId) ON DELETE CASCADE,
    FOREIGN KEY (recipeId) REFERENCES Recipes(recipeId) ON DELETE CASCADE
);
